# Site wide configuration

title:            Shubham Girdhar
locale:           en_US
url:              https://shubhamgirdhar.com
# url:              http://localhost:4000

name: SHUBHAM GIRDHAR
# description: Thoughts on statistics, data science, computational biology, education, and R

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false


# Site owner
owner:
  name: Shubham Girdhar
  avatar: "/assets/images/girdharshubham.png"
  bio: "DevOps Engineer at Knoldus, loves the Scala ecosystem"
  email: girdharshubham@hotmail.com
  disqus-shortname: 
  twitter: 
  facebook: #username
  google:
    plus: #username
    analytics: 
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: girdharshubham
  stackoverflow: 
  linkedin: girdharshubham
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
